#!/bin/bash

# Get current dir name
dir=$(basename "$PWD")

# Cleanup containers
[[ "${1:-}" == *c* ]] && docker compose down

# Cleanup volumes
[[ "${1:-}" == *v* ]] && docker volume ls -q | grep "^${dir}_" | xargs -r docker volume rm

# Cleanup logs
if [[ "${1:-}" == *l* ]]; then

  # Container logs
  for f in var/log/compose/*/*; do
    [[ ! "$f" =~ \.gitignore$ ]] && rm "$f"
  done

  # Custom logs
  rm -Rf var/log/custom/*/
  rm -Rf var/log/custom/*.log
fi

# Cleanup swap
if [[ "${1:-}" == swap ]]; then
  SWAPFILE="/swapfile-indi-engine"
  if [[ -f "$SWAPFILE" ]]; then
    swapoff "$SWAPFILE"
    rm "$SWAPFILE"
    sed -i "/^$SWAPFILE/d" /etc/fstab
  fi
fi

# Cleanup the whole app instance
if [[ "${1:-}" == "" ]]; then

  # Cleanup docker stuff
  source cleanup cv
  docker system prune -af

  # Cleanup swap
  source cleanup swap

  # Remove cd-command from bashrc
  sed -i "/^cd $(echo "$PWD" | sed 's/[\/&]/\\&/g')$/d" /root/.bashrc

  # Remove current dir
  cd ../
  rm -Rf "$dir"
fi
