#!/bin/bash

# If only logs should be cleaned up
if [[ "${1:-}" == logs ]]; then

  # Cleanup container logs
  for f in var/log/compose/*/*.log; do
    : > "$f"
  done

  # Remove custom logs
  rm -Rf var/log/custom/*/
  rm -Rf var/log/custom/*.log

# Else cleanup containers, volumes and logs
elif [[ "${1:-}" == cvl ]]; then

  # Get current dir name
  dir=$(basename "$PWD")

  # Do cleanup
  docker compose down
  docker volume ls -q | grep "^${dir}_" | xargs -r docker volume rm
  source cleanup logs

# Else cleanup swap
elif [[ "${1:-}" == swap ]]; then
  SWAPFILE="/swapfile-indi-engine"
  if [[ -f "$SWAPFILE" ]]; then
    swapoff "$SWAPFILE"
    rm "$SWAPFILE"
    sed -i "/^$SWAPFILE/d" /etc/fstab
  fi

# Else cleanup the whole app instance
else

  # Cleanup docker stuff
  docker compose down
  docker volume prune -af
  docker system prune -af

  # Cleanup swap
  source cleanup swap

  # Get current dir name
  dir=$(basename "$PWD")

  # Remove cd-command from bashrc
  sed -i "/^cd $(echo "$PWD" | sed 's/[\/&]/\\&/g')$/c\\" /root/.bashrc

  # Remove current dir
  cd ../
  rm -R "$dir"
fi